name: Delete old workflow runs

on:
  workflow_dispatch:  # Allow manual trigger if needed


jobs:
  del_runs:
    runs-on: ubuntu-latest
    permissions:
      actions: write  # Permissions to delete workflow runs
      contents: read
    steps:
      - name: Install GitHub CLI
        run: |
          sudo apt update
          sudo apt install gh

      - name: Authenticate with GitHub CLI
        run: |
          echo ${{ github.token }} | gh auth login --with-token

      - name: Delete old workflow runs
        run: |
          # Get all workflow runs older than 30 days
          gh api repos/${{ github.repository }}/actions/runs \
            --jq '.workflow_runs[] | select(.created_at < "30 days ago") | .id' | while read run_id; do
              # Delete the old workflow run
              gh api repos/${{ github.repository }}/actions/runs/$run_id --method DELETE
              echo "Deleted workflow run $run_id"
            done
