name: Delete Workflow Runs

on:
  workflow_dispatch:  # Manually trigger the workflow

jobs:
  clean_up:
    runs-on: ubuntu-latest
    permissions:
      actions: write   # Ensure write permission is set
    steps:
      - name: Get old workflow runs
        run: |
          echo "Fetching workflow runs older than 3 days"
          run_date=$(date -d '3 days ago' --utc +%Y-%m-%dT%H:%M:%SZ)
          echo "Looking for runs older than: $run_date"

          # Initialize page number and response variable
          page=1
          
          # Loop to handle pagination and fetch all workflow runs
          while true; do
            response=$(curl -H "Authorization: Bearer ${{ secrets.PAT }}" \
                             -H "Accept: application/vnd.github.v3+json" \
                             "https://api.github.com/repos/${{ github.repository }}/actions/runs?page=$page&per_page=100")

            # Check if the response contains any runs
            runs_count=$(echo "$response" | jq '.workflow_runs | length')
            if [ "$runs_count" -eq 0 ]; then
              echo "No more runs found, exiting pagination."
              break
            fi
            
            echo "Response from page $page: $response"

            # Filter and delete workflow runs older than 3 days
            echo "$response" | jq -r ".workflow_runs[] | select(.created_at < \"$run_date\") | .id" | while read run_id; do
              echo "Deleting run $run_id..."
              curl -X DELETE -H "Authorization: Bearer ${{ secrets.PAT }}" \
                  "https://api.github.com/repos/${{ github.repository }}/actions/runs/$run_id"
              echo "Deleted run $run_id"
            done
            
            # Increment the page number for the next iteration
            page=$((page + 1))
          done
