name: Maven Package

on:
  push:
    branches:
      - "*"
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      pull-requests: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github
        settings-path: ${{ github.workspace }}

    - name: Build with Maven
      id: maven-build
      run: mvn -B package --file pom.xml

    # Generate checklist results
    - name: Generate checklist results
      id: generate_checklist
      run: |
        # Define the checklist format with placeholders instead of markdown checkboxes
        checklist="## Automated PR Checklist Results:
        - Build with Maven: [ ]"
        # If the Maven build was successful, update the checklist with a checked box
        if [[ "${{ steps.maven-build.outcome }}" == "success" ]]; then
          checklist="${checklist//- Build with Maven: \[ \]/- Build with Maven: [x]}"
        fi
       
        Write-Output "Checklist Output: $checklist"
        echo "::set-output name=checklist::$checklist"
    # Debug checklist value and GitHub API URL
    - name: Debug checklist value and GitHub API URL
      run: |
        checklist="${{ steps.generate_checklist.outputs.checklist }}"
        echo "Raw output of checklist: $checklist"
        echo "Length of checklist: ${#checklist}"
        echo "Repository: ${{ github.repository }}"
        echo "PR Number: ${{ github.event.pull_request.number }}"
        echo "GitHub API URL: https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments"
    # Post checklist results as a comment on the PR
    - name: Post checklist results
      if: github.event_name == 'pull_request'
      run: |
        checklist="${{ steps.generate_checklist.outputs.checklist }}"
        body="{\"body\": \"$checklist\"}"
        url="https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments"
        headers="Authorization: token ${{ secrets.GITHUB_TOKEN }}"
        curl -X POST -H "$headers" -d "$body" "$url"
