name: Maven Package

on:
  push:
    branches:
      - "*"
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      pull-requests: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github
        settings-path: ${{ github.workspace }}

    - name: Build with Maven
      id: maven-build
      run: |
        mvn -B package --file pom.xml
        echo "Build status: $?"
      continue-on-error: true  # Continue even if the Maven build fails

    - name: Generate checklist results
      id: generate_checklist
      run: |
        # Initialize the checklist with unchecked
        checklist="## Automated PR Checklist Results:\n- Build with Maven: []"

        # Check the conclusion of the previous step
        if [[ "${{ steps.maven-build.outcome }}" == "success" ]]; then
          checklist="${checklist//\[ \]/\[x\]}"
          echo "Maven build was successful."
        fi
        echo "Checklist:\n$checklist" # For debugging
        echo "checklist=$checklist" >> $GITHUB_ENV

    - name: Debug checklist output
      run: echo -e "Checklist after generation:\n${{ env.checklist }}"
      shell: bash

    - name: Post checklist results
      if: github.event_name == 'pull_request'
      run: |
        checklist="${{ env.checklist }}"
        body="{\"body\": \"$checklist\"}"
        url="https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments"
        curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -d "$body" "$url"
