name: Maven Package

on:
  push:
    branches:
      - "*"
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      pull-requests: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github
        settings-path: ${{ github.workspace }}

    - name: Build with Maven
      id: maven-build
      run: mvn -B package --file pom.xml

    # Generate checklist results
    - name: Generate checklist results
      id: generate_checklist
      run: |
        checklist="## Automated PR Checklist Results:- Build with Maven: []"
        echo "Initial checklist: $checklist"
        if [[ "${{ steps.maven-build.outcome }}" == "success" ]]; then
          echo "Maven build was successful"
          checklist="${checklist//\[ \]/\[x\]}"
        else 
          echo "Maven build was not successful"
        fi
        echo "Final checklist: $checklist"
        echo "checklist=$checklist" >> $GITHUB_ENV

    # Debug checklist output
    - name: Debug checklist output
      run: echo "Checklist after generation: ${{ env.checklist }}"

    # Post checklist results as a comment on the PR
    - name: Post checklist results
      if: github.event_name == 'pull_request'
      run: |
        checklist="${{ env.checklist }}"
        body="{\"body\": \"$checklist\"}"
        url="https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments"
        curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -d "$body" "$url"
